### PR TITLE
Corrections, updates, and ci

### PR DESCRIPTION
**Pull request by cxhercules**

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Ah crap we do not have prow. Please backlog

**Comment by cxhercules** [comment]
What does no prow mean? 🤔

**Comment by chrislovecnm** [comment]
We use prow for bot commands. It is the CI system that k8s uses.

**Comment by cxhercules** [comment]
please test this

**Comment by cxhercules** [comment]
Closing to clean up branching and forking :|

**Pull request closed without merging**
